<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Temperatura e Humidade</title>
</head>
<body>
<h3>Temperatura e humidade</h3>
</div>
<div class="corpo-table" style="width: 800px;">
    <table class="table table-striped table-bordered table-hover">
        <thead>
        <tr>
            <th>Temperatura</th>
            <th>humidade</th>
            <th>data/hora</th>
        </tr>
        </thead>

        <tbody>
        <?php foreach ($this->resultado as  $dados): ?>
            <tr>
                <td><?php echo $this->escapeHtml($dados->temp); ?></td>
                <td><?php echo $this->escapeHtml($dados->hum); ?></td>
                <td><?php echo $this->escapeHtml($dados->data_hora); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</body>
</html>